# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    
    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest && golangci-lint run ./...
    
    - name: Test
      run: cd ${{github.workspace}}/indexer/ && go test -v ./...

    - name: Run Index
      run: export GITHUB_TOKEN="${{ secrets.CI_TOKEN }}" && cd ${{github.workspace}}/indexer/ && go run ./main.go

    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.CI_TOKEN }}
        file: ${{github.workspace}}/dist/index.json
        asset_name: index.json
        tag: index-${{github.run_number}}
        overwrite: false
        prerelease: false
        make_latest: true
        release_name: "index-${{github.run_number}}"
        body: "" 
